### ISSUE TITLE
Choose output directory

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/pagemaster#11]
Hello :)

First thanks for making this plugin. I just discovering it after having used datapage_gen and would like to check if it's better, but there are a few things which prevent me from switching to your plugin, so I'm opening this issue (and another one)

I'd like to be able to specify the output directory, because my site has 2 languages and I need to generate files for both english and french layouts, and out put in both the "en" and "fr" directories of my website structure.

As I understand it from the README the output is obviously the same if I use the same data file.

Thanks in advance.

**Comment by mnyrop** [comment]
I had a similar case with a site in both Arabic and English. I just made them separate collections, see:

https://github.com/mnyrop/sudanphoto/blob/ecd72e6a81fcf6879fa8e8090bf3419d381d587a/_config.yml#L27

In essence, naming the collections `archive/en` and `archive/ar` generate them to the directories `en` and `ar` within `archive` respectively. You would just have one data file (csv, json, or yaml) for each collection (e.g., `archive-en.csv` and `archive-ar.csv`:

```
_data/
|__ archive-en.csv
|__ archive-ar.csv
_archive/
|__en/
|____ page1.md
|____ page2.md
|__ar/
|____ page1.md
|____ page2.md
```

**Comment by AxelTerizaki** [comment]
OK, sounds fair. Thanks for the reply :)
