### ISSUE TITLE
Conditions for parsing a collection

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/pagemaster#12]
Could it be possible to apply a condition when parsing a collection ? I have a big data set and would like to avoid splitting it up depending on category.

For example my "tags" collection has a "tagtype" field. I'd like to thus make two sets of files, one for "singers" and "songwriters" for example, but both are in the "tags" collection (only their tagtype differs)

So if I want to output only singers, I'd like to specify that I only want the items which meet the condition (tagtype == singer).

**Comment by mnyrop** [comment]
With the current plugin, you would need to make `singers` and `songwriters` different collections to control them differently, or you could exclude those pages from being displayed using liquid filters. 

(They would still be built/published in the latter option, but it would be relatively easy to keep them from being indexed. I suppose it depends on your use case.)

**Comment by AxelTerizaki** [comment]
I suppose making different collections is my best bet, thanks for your answer :)
