### ISSUE TITLE
Question about ID

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/pagemaster#13]
I see the ID is what's used to determine how to call the .md files created.

Does it work with simple names? For example "John Doe" and such? Some of my data in my collection don't have static uuids which would make them real unique, but their uniqueness is their name. Is the url slugified or something if I provide a string-like id field ? Like "John Doe" becomes "john-doe.md" ? 

The reason I'm asking is because I want to be able to create links to the pages generated from other pages, so I would need a "safe" method (slugification for example) to know which URL should I point to from my page to display the "John Doe" page for instance.

Thanks for your answers.

**Comment by mnyrop** [comment]
The url will be slugified with an underscore. Try it out and let me know if it doesn't behave as expected.

https://github.com/mnyrop/pagemaster/blob/abc9ee8874892fc1d0d362188d1e4d159c375332/lib/pagemaster.rb#L87

**Comment by AxelTerizaki** [comment]
Thanks for the info, I managed to test it out a bit.

My main problem is that it doesn't handle characters with accents, like é è ô û and so on. It replaces them with nothing, resulting in names like aira_yki.md for aira_yuki.md

I think a simple

```
.tr(	"ÀÁÂÃÄÅàáâãäåĀāĂăĄąÇçĆćĈĉĊċČčÐðĎďĐđÈÉÊËèéêëĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħÌÍÎÏìíîïĨĩĪīĬĭĮįİıĴĵĶķĸĹĺĻļĽľĿŀŁłÑñŃńŅņŇňŉŊŋÑñÒÓÔÕÖØòóôõöøŌōŎŏŐőŔŕŖŗŘřŚśŜŝŞşŠšſŢţŤťŦŧÙÚÛÜùúûüŨũŪūŬŭŮůŰűŲųŴŵÝýÿŶŷŸŹźŻżŽž",	"AAAAAAaaaaaaAaAaAaCcCcCcCcCcDdDdDdEEEEeeeeEeEeEeEeEeGgGgGgGgHhHhIIIIiiiiIiIiIiIiIiJjKkkLlLlLlLlLlNnNnNnNnnNnNnOOOOOOooooooOoOoOoRrRrRrSsSsSsSssTtTtTtUUUUuuuuUuUuUuUuUuUuWwYyyYyYZzZzZz"
```

would do the trick when you try to slugify the item.

Could this be added please? :)

**Comment by mnyrop** [comment]
I can definitely do that. I'll add it to the next point release, likely in the next week.

And just a heads up, my other gem [wax_tasks](https://github.com/mnyrop/wax_tasks) has a lot more functionality, some of which might be useful to you (including diacritic normalization). Pagemaster seems like it would cover your cases but, should you outgrow it, wax_tasks is a more powerful option.

**Comment by AxelTerizaki** [comment]
Nice, thanks a lot. I'll give wax_tasks a try indeed, the search index feature could be pretty useful.
