### ISSUE TITLE
Test + upgrade to use Jekyll 4.0

### ISSUE THREAD

**Issue by mnyrop** [mnyrop/pagemaster#20]

**Comment by fer-rum** [comment]
FYI: I just modified the `pagemaster.gemspec` to require Jekyll 4.0 and it rebuilt and seems to work as intended.

**Comment by mnyrop** [comment]
That was my assessment as well, though it's good to have that result confirmed by someone else. I'll release a version that allows jekyll v4.0 soon. thanks!

**Comment by dshowland** [comment]
Any update on releasing an update that works with Jekyll 4.0? I'm not sure how to change the required Jekyll version and rebuild this myself.

**Comment by mnyrop** [comment]
@dshowland  newest version `2.1.0` was just released and uses Jekyll 4
