### ISSUE TITLE
Is there a permalink option 

### ISSUE THREAD

**Issue by mwt** [mnyrop/pagemaster#28]
Is there a way to control the permalink that gets added to each page? In my use case, I just don't want them to end in html.

**Comment by mnyrop** [comment]
@MattWThomas you can configure permalink patterns as part of Jekyll core. See: https://jekyllrb.com/docs/permalinks/
Hope it's helpful!

**Comment by mwt** [comment]
@mnyrop That one doesn't seem to allow you to control the extension (.html)

Other people might not find this feature useful though. For now, I'm just replacing the text in the permalink field using bash.

**Comment by mnyrop** [comment]
@MattWThomas i've successfully controlled the extension (in my case, ending in `/` instead of `.html`) using the config method linked above, so maybe i'm not understanding your use case?

**Comment by mwt** [comment]
@mnyrop I think that's the only change that's possible. My use is definitely odd. I want to have the permalinks end in .txt or .json instead of .html

I can do this by editing the permalink string in the files that pagemaster outputs.

**Comment by mnyrop** [comment]
@MattWThomas ahh i see. have you tried adding "permalink" as a column in your CSV or field in your JSON? that way pagemaster would add your preferred permalink as YAML front-matter to the pages and Jekyll could handle them on an item-by-item basis.

It's an interesting problem but i'm hesitant to throw code where (hopefully) configuration can do the work

**Comment by mwt** [comment]
@mnyrop That would probably work. I hadn't thought of that. In my case, it's probably easier to just keep the one line of bash in my build file that changes the permalink strings. If anyone else finds this issue looking for bash to change your permalink extension, I did:
```
sed -Ei 's/(permalink: [^\.]*)\.html\"/\1.txt\"/' _papers/*.md
```
This modifies the permalink of everything in the `papers` collection to use the `.txt` ending instead of `.html`. this line is run before building the site.
