### ISSUE TITLE
use as jekyll command

### ISSUE THREAD

**Issue by evanwill** [mnyrop/pagemaster#3]
I like the functionality of this plugin, 
just a thought: could be simpler to use implemented as a [jekyll command](https://jekyllrb.com/docs/plugins/#commands) plugin rather than fiddling around with the `pm_generate` value. Then, every time you want to build/rebuild the collection of `.md`, you could just say `jekyll pagemaster` or what ever to run the plugin one time. 

thank you.

**Comment by mnyrop** [comment]
Good point! I'm happy to test this out for a 2.0 when I find the time, but feel free to submit a PR if you get to it before I do.

Cheers,
Marii
