### ISSUE TITLE
If chinese character can be supported as file name

### ISSUE THREAD

**Issue by cnliri1** [mnyrop/pagemaster#30]
Dears,

how can I put the csv value into md content part? currently it's all in front matter. could you please advice on it?

**Comment by mnyrop** [comment]
This is not currently a feature, but you can try to create a Jekyll layout to allow this. For example, if your CSV has a field called `content` that you want to show in the content area, try adding `{{ page.content | markdownify }}` on the layout itself below the front-matter. 

If you're hoping to see the markdown before it's turned into HTML by Jekyll, unfortunately that's not currently in scope. 

I hope this is helpful!
